apiVersion: v2
name: awx
description: Helm chart for AWX 15.0.0 

type: application

version: 0.1.6
appVersion: 15.0.0

maintainers:
  - name: Lucas Hahn 
    email: lucas.hahn@novum-rgi.de

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 9.8.1
    condition: awx.database.builtIn.enabled