apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependency-track.fullname" . }}-config
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
type: Opaque
stringData: 
  application.properties: |-
    {{- if not (hasKey .Values.dependencyTrack.config.alpine "database") -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine "database" dict -}}
    {{- end -}}

    {{- if .Values.dependencyTrack.database.builtIn.postgresql.enabled -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "mode"         "external" -}} 
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "url"          (printf "jdbc:postgresql://%s/%s" (include "postgresql.dns" .) .Values.postgresql.global.postgresql.postgresqlDatabase) -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "driver"       "org.postgresql.Driver" -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "driverPath"   "/extlib/postgresql-42.2.5.jar" -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "username"     .Values.postgresql.global.postgresql.postgresqlUsername -}}
    {{- $_ := set .Values.dependencyTrack.config.alpine.database "password"     .Values.postgresql.global.postgresql.postgresqlPassword -}}
    {{- end -}}
    
    {{- /* autogenerate config */ -}}
    {{ include "dependency-track.configParse" (dict "data" .Values.dependencyTrack.config "currentName" "") | nindent 4 }}
    