apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dependency-track.selectorLabels" . | nindent 4 }}
