apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx.fullname" . }}
  labels:
    {{- include "awx.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.awx.metrics.enabled }}
  annotations:
  {{- end }}
    {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.awx.metrics.enabled }}
    {{ toYaml .Values.awx.metrics.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http 
      port: {{ .Values.service.port }}
      targetPort: 8052
  selector:
    {{- include "awx.selectorLabels" . | nindent 4 }}
