apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-http
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    {{- if  .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
    targetPort: {{ .Values.service.http.port }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
