apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awx.fullname" . }}-secrets
  labels:
    {{- include "awx.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ .Values.awx.secretKey }}
  credentials_py: |
    DATABASES = {
      'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        {{- if .Values.awx.database.builtIn.enabled }}
        'NAME': {{ .Values.postgresql.global.postgresql.postgresqlDatabase | quote }},
        'USER': {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }},
        'PASSWORD': {{ .Values.postgresql.global.postgresql.postgresqlPassword | quote }},
        'HOST': {{ include "postgresql.servicename" . | quote }},
        'PORT': {{ .Values.postgresql.global.postgresql.servicePort | quote }},
        'OPTIONS': { 'sslmode': {{ .Values.awx.database.sslMode | quote }},
                    'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        {{- else }}
        'NAME': {{ .Values.awx.database.name | quote }},
        'USER': {{ .Values.awx.database.user | quote }},
        'PASSWORD': {{ .Values.awx.database.password | quote }},
        'HOST': {{ .Values.awx.database.host | quote }},
        'PORT': {{ .Values.awx.database.port | quote }},
        'OPTIONS': { 'sslmode': {{ .Values.awx.database.sslMode | quote }},
                    'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        {{- end }}
        },
      }
    }

    BROADCAST_WEBSOCKET_SECRET = "{{ .Values.awx.secretKey | b64enc }}"

  environment_sh: |
    {{- if .Values.awx.database.builtIn.enabled }}
    DATABASE_USER={{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
    DATABASE_NAME={{ .Values.postgresql.global.postgresql.postgresqlDatabase | quote }}
    DATABASE_HOST={{ include "postgresql.servicename" . | quote }}
    DATABASE_PORT={{ .Values.postgresql.global.postgresql.servicePort | quote }}
    DATABASE_PASSWORD={{ .Values.postgresql.global.postgresql.postgresqlPassword | quote }}
    {{- else }}
    DATABASE_USER={{ .Values.awx.database.username | quote }}
    DATABASE_NAME={{ .Values.awx.database.name | quote }}
    DATABASE_HOST={{ .Values.awx.database.host | quote }}
    DATABASE_PORT={{ .Values.awx.database.port | quote }}
    DATABASE_PASSWORD={{ .Values.awx.database.password | quote }}
    {{- end}}